import type { ClassKey } from '../types/character'
import type { ClassDefinition } from '../types/class'

export const CLASSES: Record<ClassKey, ClassDefinition> = {
  warrior: {
    key: 'warrior',
    emoji: '⚔️',
    label: 'Warrior',
    rank: 'D',
    startMagic: 50000,
    desc: 'Frontline bruiser. High HP & Attack.',
    lore: 'Forged in the fires of a hundred battles, the Warrior is the backbone of any fighting force.',
    stats: { hp: 140, max_hp: 140, attack: 18, defense: 10, magic: 3, speed: 8, crit: 6 },
    image: 'warrior',
  },
  archer: {
    key: 'archer',
    emoji: '🏹',
    label: 'Archer',
    rank: 'D',
    startMagic: 50000,
    desc: 'Ranged precision. High Speed & Crit.',
    lore: 'Swift and deadly, the Archer strikes from the shadows before the enemy knows they are there.',
    stats: { hp: 95, max_hp: 95, attack: 14, defense: 6, magic: 5, speed: 18, crit: 15 },
    image: 'archer',
  },
  mage: {
    key: 'mage',
    emoji: '🔮',
    label: 'Mage',
    rank: 'C',
    startMagic: 75000,
    desc: 'Burst damage specialist. High Magic.',
    lore: 'Channeling arcane energies beyond mortal comprehension, the Mage reshapes reality itself.',
    stats: { hp: 80, max_hp: 80, attack: 8, defense: 4, magic: 22, speed: 12, crit: 10 },
    image: 'mage',
  },
  healer: {
    key: 'healer',
    emoji: '✨',
    label: 'Healer',
    rank: 'C',
    startMagic: 75000,
    desc: 'Divine support. Heals & buffs allies.',
    lore: 'Blessed by celestial forces, the Healer keeps their allies standing through the direst of battles.',
    stats: { hp: 100, max_hp: 100, attack: 7, defense: 8, magic: 18, speed: 11, crit: 7 },
    image: 'healer',
  },
  tank: {
    key: 'tank',
    emoji: '🛡️',
    label: 'Tank',
    rank: 'C',
    startMagic: 75000,
    desc: 'Unbreakable wall. Absorbs all damage.',
    lore: 'A living fortress. The Tank has never taken a step backward and never will.',
    stats: { hp: 180, max_hp: 180, attack: 10, defense: 20, magic: 2, speed: 5, crit: 3 },
    image: 'tank',
  },
  rogue: {
    key: 'rogue',
    emoji: '🌑',
    label: 'Shadow Rogue',
    rank: 'B',
    startMagic: 150000,
    desc: 'Master of stealth, poison & critical strikes.',
    lore: 'Born from the void between stars, the Shadow Rogue strikes where it hurts most.',
    stats: { hp: 90, max_hp: 90, attack: 16, defense: 5, magic: 8, speed: 22, crit: 20 },
    image: 'rogue',
  },
  chrono: {
    key: 'chrono',
    emoji: '⏳',
    label: 'Chronomancer',
    rank: 'B',
    startMagic: 150000,
    desc: 'Bends time itself. Heals & controls the field.',
    lore: 'Time is a river. The Chronomancer is the dam.',
    stats: { hp: 105, max_hp: 105, attack: 6, defense: 9, magic: 20, speed: 13, crit: 8 },
    image: 'chrono',
  },
  draconid: {
    key: 'draconid',
    emoji: '🐉',
    label: 'Draconid Warlord',
    rank: 'A',
    startMagic: 300000,
    desc: 'Born of Dragons. Devastating power & presence.',
    lore: 'Half dragon, half warrior, entirely unstoppable. The Draconid Warlord commands fear from birth.',
    stats: { hp: 160, max_hp: 160, attack: 22, defense: 12, magic: 5, speed: 10, crit: 8 },
    image: 'draconid',
  },
  crystalforged: {
    key: 'crystalforged',
    emoji: '💎',
    label: 'Crystalforged',
    rank: 'S',
    startMagic: 500000,
    desc: 'Living crystal construct. Truly unbreakable.',
    lore: 'Created in the heart of a dying star, the Crystalforged is the pinnacle of magical engineering.',
    stats: { hp: 220, max_hp: 220, attack: 12, defense: 25, magic: 3, speed: 4, crit: 2 },
    image: 'crystalforged',
  },
}

export const BOSS_POOL = [
  { name: 'Void Leviathan',  emoji: '🌊', hp: 5000,  reward_xp: 500,  reward_magic: 500000  },
  { name: 'Infernal Drake',  emoji: '🔥', hp: 8000,  reward_xp: 800,  reward_magic: 800000  },
  { name: 'Chrono Lich',     emoji: '💀', hp: 12000, reward_xp: 1200, reward_magic: 1200000 },
  { name: 'Abyss Colossus',  emoji: '🌑', hp: 20000, reward_xp: 2000, reward_magic: 2000000 },
]

export const ITEM_DATA = {
  weapon: [
    { name: 'Shadowblade' },
    { name: 'Voidstaff' },
    { name: 'Stormbow' },
    { name: 'Ironmaul' },
    { name: 'Crystalwand' },
    { name: 'Flamedagger' },
    { name: 'Dragonscythe' },
    { name: 'Voidreaper' },
  ],
  helmet: [
    { name: 'Starforged Helm' },
    { name: 'Voidcrown' },
    { name: 'Shadow Hood' },
    { name: 'Crystal Visor' },
    { name: 'Dragon Helm' },
    { name: 'Runic Circlet' },
    { name: 'Chaos Mask' },
    { name: 'Celestial Crown' },
  ],
  armor: [
    { name: 'Duskplate' },
    { name: 'Spiritweave' },
    { name: 'Shadowmail' },
    { name: 'Voidcloak' },
    { name: 'Dragonscale Armor' },
    { name: 'Crystal Carapace' },
    { name: 'Runeshield' },
    { name: 'Celestial Vest' },
  ],
}

export const DAILY_QUESTS_POOL = [
  { key: 'complete_mission', desc: 'Complete any mission',         reward: 50000,  target: 1 },
  { key: 'complete_hard',    desc: 'Complete a Hard/Epic mission', reward: 150000, target: 1 },
  { key: 'win_pvp',          desc: 'Win a PvP battle',             reward: 100000, target: 1 },
  { key: 'win_pvp_3',        desc: 'Win 3 PvP battles',            reward: 300000, target: 3 },
  { key: 'upgrade_item',     desc: 'Upgrade an item',              reward: 75000,  target: 1 },
  { key: 'sell_item',        desc: 'List an item on the market',   reward: 50000,  target: 1 },
]
